enabled-treecapacitor: true
enabled-autosmelter: true
# Server
motd: "&a&lWitaj!"
welcome-message: "&aWitaj, %player% na serwerze!"
join-message: "&a+ %player%"
quit-message: "&c- %player%"
chat-prefix: "&#a25981%player%&f"