name: VanillaPlus
version: '${project.version}'
main: com.drakula.vanillaplus.VanillaPlus
api-version: '1.20'
authors:
  - MODERR
  - UtkajGofra
commands:
  vanillaplus:
    aliases: vp
    permission: vanillaplus.admin
  Sethome:
    description: Sets a home location
  Home:
    description: Teleports to home
permissions:
  vanillaplus.admin:
    default: op
